// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCllThQSeWspLQrVPjHTjbGNQa793YXYC4',
    appId: '1:482118438090:android:79d27834c63e78e686f833',
    messagingSenderId: '482118438090',
    projectId: 'ecommerce-8c757',
    storageBucket: 'ecommerce-8c757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6lZJAndUecxFcU7m0nKydE9ZLFMyz0g',
    appId: '1:482118438090:ios:51ecefd6be61adbd86f833',
    messagingSenderId: '482118438090',
    projectId: 'ecommerce-8c757',
    storageBucket: 'ecommerce-8c757.appspot.com',
    androidClientId: '482118438090-cr0lkmv3v1de5q3s4s37gmt9tngn378l.apps.googleusercontent.com',
    iosClientId: '482118438090-2dj1kdd8bjqlm9cu93gbl9uqst9n74g8.apps.googleusercontent.com',
    iosBundleId: 'com.ios.bubdle',
  );
}
